language: c
notifications:
  email: false
sudo: false
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    packages:
    - llvm-3.7
install:
  - if [[ "${LLVM_CONFIG}" == *3\.[7]* ]]; then export CC="gcc-4.9"; export CXX="g++-4.9"; fi
env:
  - LLVM_CONFIG="llvm-config-3.7"
script:
  - make -f build-bc/Makefile
  - make clean
  - make -f build-clang/Makefile
  - make clean
  - make -f build-ll/Makefile
